title: hy-push-state
email: mail@qwtel.com

description: >
  Turn static web sites into dynamic web apps.
url: https://hydecorp.github.io
baseurl: /push-state

author:
  email: mail@qwtel.com
  social:
    github: https://github.com/hydecorp/push-state
    npm: https://www.npmjs.com/package/@hydecorp/push-state
    download: https://github.com/hydecorp/push-state/releases

logo: /assets/icons/icon.svg

copyright: © 2018 Florian Klampfer

permalink: pretty

google_analytics: UA-84025722-4

accent_color: "#4fb1ba"
accent_image:
  background: "linear-gradient(to bottom,#193747 0%,#233e4c 30%,#3c929e 50%,#d5d5d4 70%,#cdccc8 100%)"
  overlay: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-titles-from-headings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
  - scripts
include:
  - LICENSE.md

remote_theme: qwtel/hydejack

hydejack:
  no_mark_external: true

defaults:
  - scope:
      path: usage/README.md
    values:
      menu: true
      order: 1
  - scope:
      path: doc/README.md
    values:
      menu: true
      order: 2
  - scope:
      path: example/README.md
    values:
      menu: true
      order: 3
  - scope:
      path: licenses/README.md
    values:
      menu: true
      order: 4

titles_from_headings:
  strip_title: true
  collections: true

relative_links:
  collections: true

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

data_social:
  github:
    name: GitHub
    icon: icon-github
  npm:
    name: npm
    icon: icon-npm
  download:
    name: Download
    icon: icon-box-add
  email:
    name: Email
    icon: icon-mail

keywords:
  - page-transitions
  - ajax
  - pjax
  - smoothstate
  - hydejack
  - vanilla
  - jquery
  - animations
  - rxjs
  - vanilla-js
  - custom-element
  - jquery-plugin
  - history-api
  - web-components
  - webcomponent
  - history-management
  - prefetch
  - page-loader
  - prefetcher
  - reactive
